---
environment: prod
name: moonriver
image: {repository: eu.gcr.io/substrate-infra/mbelt2_streamer_moonbeam, tag: 6566b0be73679189f51a2bfc6b720eac93ec366f}
limits: {cpu: 700m, memory: 2Gi}
requests: {cpu: 500m, memory: 2Gi}
port: 3000
metrics:
  enabled: true
vault:
  role: "mbelt"
  secret: "secret/mbelt/v2_prod"
env:
  substrate_uri: ws://moonriver-ssd-node.moonriver.svc.cluster.local:9945
  log_level: warn
  preload: true
  subscribe: true
  start_block_id: 0
  network: moonriver
ingress:
  enabled: true
  class: nginx-external
  host: mbelt-moonriver.polka.p2p.world
  tls:
    cluster_issuer: cloudflare-prod
    secret: mbelt-moonriver-polka-p2p-world
    ssl_redirect: true
